# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d171fa8d7cb01334e4f21ba381a405c17596bacdca5f1ce92de23c1ee4d3fd28c3856b05e01bffe5ffae44dc2bb27fd69b89b0d1474927468ccbf6a8f1a97a9

test:
  secret_key_base: 1a8e10536616499f450d8404ab7de4a6e87314c2f96b6061a6292c90e13432354c15d63b0b900e1ebcdbfa4f4ccf794255164ebc41a224f90a5f3ebc726e8dae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
